version: '3.8'

services:
  libreria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/libreria_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
    volumes:
      - h2_data:/data
    restart: unless-stopped

volumes:
  h2_data:
    driver: local
